"""Initial migration

Revision ID: 154f754439c3
Revises: 
Create Date: 2025-05-08 23:33:03.195508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '154f754439c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime_records', schema=None) as batch_op:
        batch_op.alter_column('crime_id',
               existing_type=mysql.BIGINT(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id', 'role'], unique=True)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('crime_records', schema=None) as batch_op:
        batch_op.alter_column('crime_id',
               existing_type=mysql.BIGINT(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
